Automate composer install & optimise IO
nihruk/console pull request #73
Opened 2023-07-04 08:51 UTC by mdbudd

Noticed Symfony has been very slow to respond consistently and been looking into why this might be happening. It was obvious during the addition on the ELK stack that it was just Symfony that was the problem and found that installation via composer was not happening in the current PHP service. This has been added in this PR and volumes optimized to reflect the vendor file which both automates the process and speeds up io requests to the vendor file. Speed should noticeably improve..

2023-07-04 09:00 UTC, baldygeezer requested changes
Looks good. At the moment the composer install step happens in the build script: /bin/dev-build
That will also need changing.

2023-07-04 09:44 UTC, bartfeenstra requested changes

2023-07-04 09:44 UTC, bartfeenstra commented on Dockerfile
> +RUN composer install
The application must not be installed into the container image for dev environments. That should (in the near future) only be done for deployments where we do not need to do any development work (e.g. prod)

2023-07-04 09:44 UTC, bartfeenstra commented on docker-compose.yml
> +      - /srv/ioda/vendor
Is that a correct volume definition? As far as I understand Docker, each volume definition should have at least two 'fields' within the string value, separated by a colon.

2023-07-04 10:27 UTC, mdbudd commented on docker-compose.yml
> +      - /srv/ioda/vendor
Yes it is, you don't have to have two fields, you can have a direct bind.

2023-07-10 10:45 UTC, AndreaLDavies approved these changes

2023-07-24 11:46 UTC, bartfeenstra commented on docker-compose.yml
> +      - /srv/ioda/vendor
What does it bind to in such cases? Same path on the host as inside the container?

2023-07-24 11:48 UTC, bartfeenstra commented on docker-compose.yml
> +  metricbeat01:
This service should get a more descriptive name that explains what the service's purpose is.

2023-07-24 11:49 UTC, bartfeenstra commented on docker-compose.yml
> +  logstash01:
Do we expect additional Logstash services?

2023-07-24 11:49 UTC, bartfeenstra commented on docker-compose.yml
> +      # - "./elk/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro"
No commented-out code.

2023-07-24 11:49 UTC, bartfeenstra commented on docker-compose.yml
> +      # - "./elk/logstash.yml:/usr/share/logstash/config/logstash.yml:ro"
No commented-out code.

2023-07-24 11:49 UTC, bartfeenstra commented on docker-compose.yml
> +#    network_mode: host
No commented-out code.

2023-07-24 11:50 UTC, bartfeenstra commented on elk/filebeat_ingest_data/Air_Quality.log
Should this file be in our repo?

2023-07-24 11:50 UTC, bartfeenstra commented on elk/logstash/drv/mssql-jdbc-12.2.0.jre8.jar
Let's remove this file from our repo, and download it during the build process instead.

2023-07-24 11:51 UTC, bartfeenstra commented on elk/pipelines.yml
> +# - pipeline.id: DEV_ioda_awards.conf
No unused code.

2023-07-24 11:51 UTC, bartfeenstra commented on parse.js
> +// console.log(parser.parse(query))
No unused code.

2023-07-24 11:51 UTC, bartfeenstra commented on parse.js
> +// query = "doe AND 1212 AND !foo"
No unused code.

2023-07-24 11:52 UTC, bartfeenstra commented on parse.js
> +console.log(out)
No debugging code.

2023-07-24 11:52 UTC, bartfeenstra commented on parse.js
> +console.log("out")
No debugging code.

2023-07-24 11:52 UTC, bartfeenstra commented on server.js
What is this file used for?

2023-07-24 11:52 UTC, bartfeenstra commented on server.js
> +    // query = query.q.slice(0, -1).replace(/\r?\n|\r/g, "")
No unused code.

2023-07-24 11:53 UTC, bartfeenstra commented on src/Controller/LuceneController.php
Is this controller a test fixture?

2023-07-24 11:54 UTC, bartfeenstra commented on src/Controller/LuceneController.php
> +        $response = $httpClient->request('GET', 'http://node:8081/parse?q=' . $query);
Let's put the bit where we have a Lucene query string parsed in an API function, and add an integration test for it.

2023-08-15 08:17 UTC, bartfeenstra commented on docker-compose.yml
> +      - /srv/ioda/vendor
Can you link the specific docs for this syntax? Can't seem to find it myself.

2023-08-15 09:16 UTC, bartfeenstra commented
I added https://github.com/nihruk/console/issues/80 as a follow-up.

2023-08-15 10:42 UTC, bartfeenstra approved these changes

2023-08-15 10:55 UTC, merged