Docker optimisation
nihruk/console pull request #95
Opened 2023-09-25 10:29 UTC by baldygeezer

2023-10-02 10:52 UTC, bartfeenstra requested changes

2023-10-02 10:52 UTC, bartfeenstra commented on docker/php/Dockerfile
> +RUN echo "opcache.memory_consumption=256" >> /usr/local/etc/php/conf.d/docker-php-ext-opcache.ini && \
This may be cleaner by adding a configuration file to the repo, and `COPY`ing it into `/usr/local/etc/php/conf.d`

2023-10-04 10:14 UTC, baldygeezer commented on docker/php/Dockerfile
> +RUN echo "opcache.memory_consumption=256" >> /usr/local/etc/php/conf.d/docker-php-ext-opcache.ini && \
good call, done.

2023-10-09 13:45 UTC, bartfeenstra requested changes

2023-10-11 11:34 UTC, mdbudd requested changes

2023-10-11 11:34 UTC, mdbudd commented on docker-compose.yml
> +      - ./vendor:/srv/ioda/vendor
Unless there is a specific reason to add this, please remove as it increases load times in development. Possibly add production only option?

2023-10-11 11:34 UTC, mdbudd commented on vendor/.keep
Is there a reason to keep this folder? Can't see a situation it wouldn't be generated automatically.

2023-10-16 09:33 UTC, baldygeezer commented on docker-compose.yml
> +      - ./vendor:/srv/ioda/vendor
The reason this is using a bind mount is because in the dev environment we need local access to the vendor folder for code completion in the IDE (see https://github.com/nihruk/console/issues/92). Without it the IDE can’t locate classes. Using volumes in the production env is definitely the way to go though.

2023-10-16 13:07 UTC, bartfeenstra requested changes

2023-10-16 13:07 UTC, bartfeenstra commented on docker-compose.yml
> +      - ./vendor:/srv/ioda/vendor
In prod, all code must be baked into the image. The only volumes we'd need then are for runtime data.

2023-10-16 13:07 UTC, bartfeenstra commented on docker/php/opcache_jit_dev.ini
> +opcache.memory_consumption=256
This file should then be in a directory specifically for `*.ini` files, so they can be copied into the image in one fell swoop.

2023-10-16 13:07 UTC, bartfeenstra commented on vendor/.keep
Can you make a note in the `.keep` file that explains *why* the directory is to be kept in Git? Asking for our future selves :)

2023-10-17 13:37 UTC, baldygeezer commented on vendor/.keep
Note added to keepfile. The reason to keep this folder is that when opening a fresh clone in PHPstorm, the IDE detects a missing vendor folder and prompts to run composer install. This is could result in the command being run with the host PHP installation.

2023-10-17 14:16 UTC, mdbudd commented on vendor/.keep
Not overly an issue per se, however, a project contents shouldn't be dictated by the chosen IDE and if required by the IDE, `composer install` could be run to automatically generate it. The consensus of the team is fine.

2023-10-18 07:51 UTC, bartfeenstra requested changes

2023-10-18 07:51 UTC, bartfeenstra commented on docker/php/ini/base/.keep
> +config for all envs
Is there any use of this directory at all, even runtime? If not, we should remove it (no unused code).

2023-10-18 07:51 UTC, bartfeenstra commented on docker/php/ini/prod/.keep
> +production only config
Is there any use of this directory at all, even runtime? If not, we should remove it (no unused code).

2023-10-18 09:33 UTC, baldygeezer commented on vendor/.keep
I had thought that this was also an issue in vs code, but just checked again and apparently not. Agree we shouldn't let jetbrains influence the project structure...

2023-10-18 09:49 UTC, bartfeenstra approved these changes

2023-10-18 09:56 UTC, bartfeenstra approved these changes

2023-10-18 09:57 UTC, mdbudd requested changes

2023-10-18 11:07 UTC, baldygeezer commented on docker-compose.yml
> -      - ./vendor:/srv/ioda/vendor
the vendor mount was removed as it is overlapping so this is out of date now

2023-10-19 12:06 UTC, merged